### ISSUE TITLE
Inconsistencies in successive changes to the amount

### ISSUE THREAD

**Issue by SamuelGuillemet** [Clochette-AbsINThe/clochette#119]
Lorsque que l'on fait 2 transactions en simultanés, le montant de la trésorerie n'est pas correctement modifié.
Je pense que c'est lié à un problème de concurrence sur la modification du champ.

**Comment by xanode** [comment]
Tu peux fournir un exemple ?

**Comment by SamuelGuillemet** [comment]
La routine pour reproduire le bug c'est :
- Se connecter avec le compte admin
- Se rendre sur `/account/tresory/`
- Cliquer sur modifier le montant, de la carte compte
- Ajouter un montant de départ de 100€
- Demander à faire un retrait d'argent de 50€
- Les montants de la carte totale ne sont pas juste

**Comment by SamuelGuillemet** [comment]
The bug is still present on _dev_ branch

**Comment by SamuelGuillemet** [comment]
![image](https://user-images.githubusercontent.com/60295745/225780681-5aaabbfe-21d2-4eb1-95a8-1afe70d526cd.png)

---

En refaisant les calculs ont a :

2500 - 711 - 400 - 37.25 + (5.5 * 0.985) + (3.5 * 0.985) + 9 + 50 - 50 = 1369.615
