### ISSUE TITLE
Prevent transactions from being created if cash amount is not enough

### ISSUE THREAD

**Issue by xanode** [Clochette-AbsINThe/clochette#61]
Lorsqu'un item est acheté, par exemple un hors-stock, il est créé **avant** la transaction. Or, quand le paiement s'effectue en espèce et que la transaction engendre un montant en espèce négatif (ce qui n'est pas possible), elle est refusée par le backend (erreur 400). De fait, un item est créé sans qu'il n'y ait eu de transaction.

Ainsi il faut :

- [ ] S'assurer que le montant en espèce ne sera pas négatif
- [ ] Faire la transaction et tout le bazarre

**Comment by SamuelGuillemet** [comment]
Mais ducoup ça voudrais dire qu'un mec paye en liquide sans avoir l'argent ce qui est pas possible en vrai nan ?
---
De ce que j'ai compris, si c'est une transaction d'achat en liquide il faut que je fasse un GET sur /treasury/ et que je vérifie que `amount` soit bien inférieur au `totalCash` ?
---
> De fait, un item est créé sans qu'il n'y ait eu de transaction.
Je m'était attendu à ce que le `db.rollback()` supprime l'item nan ?

**Comment by xanode** [comment]
Ce n'est pas possible qu'Absinthe paye en liquide sans avoir le montant nécessaire, d'où le problème.

Tu peux faire un `GET` sur `/treasury/` et t'assurer que `cashAmount` moins le montant de la transaction est positif.

L'item tu le créé via une requête, pas via la transaction (dans le cas de `out_of_stock_item`), et c'est ce qui pose problème. S'il n'y avait que la transaction il n'y aurait pas de problème.

**Comment by SamuelGuillemet** [comment]
Ah oui je vois mais ce comportement est voulu, l'item créer n'a pas de lien avec la tréso donc vaut mieux le sauvegarder en base quand même. Par exemple si c'est juste une erreur de mode de paiement, bah l'item existe déjà et il va pouvoir être référencé comme fkId.
Je comprend pas trop pourquoi il faudrait rajouter l'information à la main sachant que le toast dans le front renvoie déjà le fait que ya pas assez de cash dans la tréso

**Comment by xanode** [comment]
C'est pas très lisible pour un utilisateur, de voir l'erreur puis la justification en anglais pendant quelques secondes dans un coin de l'écran.

**Comment by SamuelGuillemet** [comment]
Bah met les justifications en français dans le backend alors !

**Comment by SamuelGuillemet** [comment]
Des nouvelles sur la traduction des erreurs dans le backend ?
