### ISSUE TITLE
Add query parameters support in various endpoints

### ISSUE THREAD

**Issue by SamuelGuillemet** [Clochette-AbsINThe/clochette#86]
- [x] **barrel_id**  sur l'endpoint `/glass/`
- [x] **sale** sur l'endpoint `/transaction/`
- [x] **created_at** sur l'endpoint `/transaction/` - _sur celui ci il faut un filtre avec des >= et <= pour récupérer les transactions sur un intervalle_
- [x] **is_active** sur l'endpoint `/account/`
---
### Edit
- [x] **name** sur l'endpoint `/out_of_stock_item/buy/`
- [x] **name** sur l'endpoint `/out_of_stock_item/sell/`

**Comment by xanode** [comment]
Les paramètres sur lesquels le filtrage est autorisé sont plus nombreux que ceux que tu as spécifiés.
