### ISSUE TITLE
Add Lydia rate support and transaction typing and description

### ISSUE THREAD

**Issue by SamuelGuillemet** [Clochette-AbsINThe/clochette#87]
Il faudrait pouvoir ajouter un PUT sur la `treasury` pour que le tréso puisse modifier les montants de la tréso facilement.

Pour garder trace de ça, on devrait ajouter un historique de la tréso.

**Comment by xanode** [comment]
Il faut modifier le schéma de la base de données pour ça #3

**Comment by SamuelGuillemet** [comment]
Il faut ajouter le taux de conversion Lydia dans la table trésorerie et rendre les champs modifiables par le PUT optionnels

**Comment by SamuelGuillemet** [comment]
Ne laisser que le champs taux lydia modifiable.
Il faut rajouter un champs type dans la table transaction qui possède une Enum : 
- Tresory
- Transaction

**Comment by SamuelGuillemet** [comment]
Maybe add a way to revert transactions ?
