### ISSUE TITLE
Refactor endpoints for barrels

### ISSUE THREAD

**Issue by SamuelGuillemet** [Clochette-AbsINThe/clochette#95]
The endpoints for barrels could be refactor to :
- barrel/?_queryParameters_ (to replace *all,* *mounted*, and *barrel*)
- barrel/distincts/

**Comment by SamuelGuillemet** [comment]
When making a request with query parameter all=True, should return all the barrels.
Actually you can only get mounted or non mounted barrels but not all of them.

**Comment by xanode** [comment]
Est-ce que j'ajoute un paramètre de requête `empty` pour filtrer si le fût est vide ou non ?

**Comment by SamuelGuillemet** [comment]
non je pense pas
